version: "3"

services:
  web:
    environment:
      NODE_ENV: development
      RAILS_ENV: staging
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      DB_PORT: 3306
    build:
      context: .
      dockerfile: Dockerfile.staging
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        APP_DIR: /solidus_test

    command: bash -c "rm -f tmp/pids/server.pid &&
      ./bin/webpack-dev-server &
      bundle exec rails server puma -p 3000 -b '0.0.0.0'"

    volumes:
      # make sure this lines up with APP_DIR above
      - .:/solidus_test

    ports:
      - "3000:3000"
