version: "3"

services:
  solidus_test:
    env_file: .env
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        APP_DIR: /solidus_test

    command: bash -c "rm -f tmp/pids/server.pid &&
      ./bin/webpack-dev-server &
      bundle exec rails server -p 3000 -b '0.0.0.0'"

    volumes:
      # make sure this lines up with APP_DIR above
      - .:/solidus_test

    ports:
      - "3000:3000"

    depends_on:
      - db

  db:
    image: mysql:5.7
    expose:
      - '3306'
    volumes:
      - db_data:/var/run/mysqld
    logging:
      driver: none
    ports:
      - 3306

volumes:
  db_data:
