FROM ruby:2.7.2 as builder

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

FROM builder as rails-app

EXPOSE 3001

ARG APP_DIR=/buddy/solidus_test
WORKDIR $APP_DIR

ARG SECRET_KEY_BASE=d5eb5837e545a3022d28f055e55b6a26326453bdfcc269bf347a3ba919dcf06088c84179dfd7d3af56480a41b6bd35bd1d0bcae225511d3b3ac7067f22e49857

CMD ["rails", "server", "-b", "0.0.0.0"]
#RUN RAILS_ENV=staging SECRET_KEY_BASE=$SECRET_KEY_BASE bundle exec rake assets:precompile
