default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'mysql2' %>
  encoding: utf8mb4
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: solidus_test_development
  socket: /var/run/mysqld/mysqlx.sock

test:
  <<: *default
  database: solidus_test_test

staging:
  <<: *default

production:
  <<: *default
